/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        primary: "#0970D7",
        light: " #50A3F7",
        middark: "#101011",
        dark: "#111111",
        deep: "#000000",
        ordinary: "#40C1AD",
        header: "#07529D",
        secondary: "#f3a712",
        error: "#FF3333",
        white: "#fff",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    textColor: {
      primary: "#0970D7",
      light: " #50A3F7",
      middark: "#101011",
      dark: "#111111",
      deep: "#000000",
      ordinary: "#40C1AD",
      header: "#07529D",
      secondary: "#f3a712",
      error: "#FF3333",
      white: "#fff",
    },
    backgroundColor: {
      primary: "#0970D7",
      light: " #50A3F7",
      middark: "#101011",
      dark: "#111111",
      deep: "#000000",
      ordinary: "#40C1AD",
      header: "#07529D",
      secondary: "#f3a712",
      error: "#FF3333",
      white: "#fff",
    },
    borderColor: {
      primary: "#0970D7",
      light: " #50A3F7",
      middark: "#101011",
      dark: "#111111",
      deep: "#000000",
      ordinary: "#40C1AD",
      header: "#07529D",
      secondary: "#f3a712",
      error: "#FF3333",
      white: "#fff",
    },
    outlineColor: {
      primary: "#0970D7",
      light: " #50A3F7",
      middark: "#101011",
      dark: "#111111",
      deep: "#000000",
      ordinary: "#40C1AD",
      header: "#07529D",
      secondary: "#f3a712",
      error: "#FF3333",
      white: "#fff",
    },
  },
  plugins: [require("tailwindcss-animate")],
};
